In [1]:
import pandas as pd
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
resume_data = [
    {"candidate_id": 1, "resume_text": "Aarav has skills in Python, SQL, Excel, and Machine Learning. He has 3 years of experience. Education: B.Tech. Certifications: 2."},
    {"candidate_id": 2, "resume_text": "Diya has skills in Recruitment, Onboarding, Communication, and Excel. She has 4 years of experience. Education: MBA HR. Certifications: 1."},
    {"candidate_id": 3, "resume_text": "Kabir has skills in Python, SQL, Tableau, Data Analysis, and Pandas. He has 2 years of experience. Education: B.Sc. Certifications: 3."},
    {"candidate_id": 4, "resume_text": "Ishita has skills in Java, SQL, Spring, Teamwork, and Communication. She has 5 years of experience. Education: B.Tech. Certifications: 2."},
    {"candidate_id": 5, "resume_text": "Vivaan has skills in Python, SQL, Deep Learning, NLP, and BERT. He has 6 years of experience. Education: M.Tech. Certifications: 4."},
    {"candidate_id": 6, "resume_text": "Anaya has skills in Recruitment, Sourcing, Interview Screening, and Communication. She has 3 years of experience. Education: MBA HR. Certifications: 2."},
    {"candidate_id": 7, "resume_text": "Reyansh has skills in Python, SQL, Power BI, Excel, and Statistics. He has 4 years of experience. Education: B.Tech. Certifications: 2."},
    {"candidate_id": 8, "resume_text": "Myra has skills in Machine Learning, Python, Tableau, and Data Visualization. She has 2 years of experience. Education: M.Sc. Certifications: 3."},
    {"candidate_id": 9, "resume_text": "Arjun has skills in Manual Testing, Selenium, Jira, and Communication. He has 5 years of experience. Education: BCA. Certifications: 1."},
    {"candidate_id": 10, "resume_text": "Siya has skills in Python, SQL, NLP, ML, Communication, and Teamwork. She has 3 years of experience. Education: MCA. Certifications: 3."},
    {"candidate_id": 11, "resume_text": "Krish has skills in Excel, SQL, Dashboarding, Reporting, and Power BI. He has 2 years of experience. Education: B.Com. Certifications: 2."},
    {"candidate_id": 12, "resume_text": "Aadhya has skills in Python, R, Statistics, and Machine Learning. She has 4 years of experience. Education: M.Stat. Certifications: 3."},
    {"candidate_id": 13, "resume_text": "Advik has skills in Project Management, Agile, Scrum, and Communication. He has 6 years of experience. Education: MBA. Certifications: 2."},
    {"candidate_id": 14, "resume_text": "Kiara has skills in Python, SQL, Data Analysis, Recruitment, and HR Analytics. She has 5 years of experience. Education: MBA HR. Certifications: 4."},
    {"candidate_id": 15, "resume_text": "Atharv has skills in C++, Algorithms, Data Structures, and Problem Solving. He has 1 year of experience. Education: B.Tech. Certifications: 1."},
    {"candidate_id": 16, "resume_text": "Navya has skills in Python, SQL, Tableau, Power BI, and Communication. She has 3 years of experience. Education: BBA. Certifications: 2."},
    {"candidate_id": 17, "resume_text": "Rudra has skills in NLP, BERT, Transformers, Python, and Machine Learning. He has 5 years of experience. Education: M.Tech. Certifications: 4."},
    {"candidate_id": 18, "resume_text": "Sara has skills in Recruitment Analytics, Excel, Communication, and HR Operations. She has 4 years of experience. Education: MBA HR. Certifications: 2."},
    {"candidate_id": 19, "resume_text": "Vihaan has skills in Python, SQL, Statistics, Data Cleaning, and Pandas. He has 2 years of experience. Education: B.Sc. Certifications: 2."},
    {"candidate_id": 20, "resume_text": "Meera has skills in Python, Machine Learning, SQL, Communication, and Dashboards. She has 4 years of experience. Education: MCA. Certifications: 3."}
]

df = pd.DataFrame(resume_data)
df.head()

   candidate_id                                        resume_text
0             1  Aarav has skills in Python, SQL, Excel, and Ma...
1             2  Diya has skills in Recruitment, Onboarding, Co...
2             3  Kabir has skills in Python, SQL, Tableau, Data...
3             4  Ishita has skills in Java, SQL, Spring, Teamwo...
4             5  Vivaan has skills in Python, SQL, Deep Learnin...

In [3]:
print("Dataset shape:", df.shape)
print("Columns:", list(df.columns))

Dataset shape: (20, 2)
Columns: ['candidate_id', 'resume_text']

In [4]:
df.head(3)

   candidate_id                                        resume_text
0             1  Aarav has skills in Python, SQL, Excel, and Ma...
1             2  Diya has skills in Recruitment, Onboarding, Co...
2             3  Kabir has skills in Python, SQL, Tableau, Data...

In [5]:
def extract_skills(text):
    match = re.search(r"skills in (.*?)[.] He has|skills in (.*?)[.] She has", text, re.IGNORECASE)
    if match:
        return match.group(1) if match.group(1) else match.group(2)
    return ""

df["skills_extracted"] = df["resume_text"].apply(extract_skills)

In [6]:
def extract_experience(text):
    match = re.search(r"(\d+)\s+years of experience", text, re.IGNORECASE)
    return int(match.group(1)) if match else 0

df["experience_extracted"] = df["resume_text"].apply(extract_experience)

In [7]:
def extract_experience(text):
    match = re.search(r"(\d+)\s+years of experience", text, re.IGNORECASE)
    return int(match.group(1)) if match else 0

df["experience_extracted"] = df["resume_text"].apply(extract_experience)

In [8]:
def extract_education(text):
    match = re.search(r"Education:\s*([A-Za-z. ]+)", text)
    return match.group(1).strip() if match else ""

df["education_extracted"] = df["resume_text"].apply(extract_education)

In [9]:
def extract_certifications(text):
    match = re.search(r"Certifications:\s*(\d+)", text)
    return int(match.group(1)) if match else 0

df["certifications_extracted"] = df["resume_text"].apply(extract_certifications)

In [10]:
job_description = "python sql machine learning nlp communication recruitment analytics power bi"

In [11]:
required_keywords = ["python", "sql", "machine learning", "nlp", "communication", "recruitment", "analytics", "power bi"]

def keyword_match_count(skill_text):
    skill_text = skill_text.lower()
    return sum(1 for k in required_keywords if k in skill_text)

df["keyword_match_count"] = df["skills_extracted"].apply(keyword_match_count)

In [12]:
documents = [job_description] + df["skills_extracted"].tolist()

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

In [13]:
similarity_scores = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()
df["similarity_score"] = similarity_scores

In [14]:
df["experience_score"] = df["experience_extracted"] / df["experience_extracted"].max()
df["certification_score"] = df["certifications_extracted"] / df["certifications_extracted"].max()

In [15]:
education_map = {
    "B.Com": 0.50, "BBA": 0.55, "BCA": 0.55, "B.Sc": 0.60,
    "B.Tech": 0.70, "MBA": 0.75, "MBA HR": 0.80,
    "MCA": 0.80, "M.Sc": 0.80, "M.Tech": 0.90, "M.Stat": 0.90
}

df["education_score"] = df["education_extracted"].map(education_map)

In [16]:
df["keyword_score"] = df["keyword_match_count"] / len(required_keywords)

df["final_score"] = (
    0.30 * df["keyword_score"] +
    0.30 * df["similarity_score"] +
    0.20 * df["experience_score"] +
    0.10 * df["education_score"] +
    0.10 * df["certification_score"]
)

In [17]:
ranked_df = df.sort_values(by="final_score", ascending=False).reset_index(drop=True)
ranked_df.head()

   candidate_id                                        resume_text                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted  keyword_match_count  similarity_score  experience_score  certification_score  education_score  keyword_score  final_score
0             1  Aarav has skills in Python, SQL, Excel, and Ma...           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2                    3          0.432462          0.500000                 0.50              NaN          0.375          NaN
1             2  Diya has skills in Recruitment, Onboarding, Co...  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1                    2          0.232806          0.666667                 0.25              NaN          0.250          NaN
2             3  Kabir has skills in Python, SQL, Tableau, Data...    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3                    2          0.107773          0.333333                 0.75              NaN          0.250          NaN
3             4  Ishita has skills in Java, SQL, Spring, Teamwo...     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2                    2          0.122363          0.833333                 0.50              NaN          0.250          NaN
4             5  Vivaan has skills in Python, SQL, Deep Learnin...          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4                    3          0.354681          1.000000                 1.00              NaN          0.375          NaN

In [18]:
top_5 = ranked_df.head(5)
top_5

   candidate_id                                        resume_text                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted  keyword_match_count  similarity_score  experience_score  certification_score  education_score  keyword_score  final_score
0             1  Aarav has skills in Python, SQL, Excel, and Ma...           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2                    3          0.432462          0.500000                 0.50              NaN          0.375          NaN
1             2  Diya has skills in Recruitment, Onboarding, Co...  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1                    2          0.232806          0.666667                 0.25              NaN          0.250          NaN
2             3  Kabir has skills in Python, SQL, Tableau, Data...    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3                    2          0.107773          0.333333                 0.75              NaN          0.250          NaN
3             4  Ishita has skills in Java, SQL, Spring, Teamwo...     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2                    2          0.122363          0.833333                 0.50              NaN          0.250          NaN
4             5  Vivaan has skills in Python, SQL, Deep Learnin...          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4                    3          0.354681          1.000000                 1.00              NaN          0.375          NaN

In [19]:
def label_candidate(score):
    if score >= 0.65:
        return "Strong Fit"
    elif score >= 0.50:
        return "Moderate Fit"
    else:
        return "Low Fit"

ranked_df["recommendation"] = ranked_df["final_score"].apply(label_candidate)

In [20]:
final_output = ranked_df[[
    "candidate_id",
    "resume_text",
    "skills_extracted",
    "experience_extracted",
    "education_extracted",
    "certifications_extracted",
    "keyword_match_count",
    "keyword_score",
    "similarity_score",
    "experience_score",
    "education_score",
    "certification_score",
    "final_score",
    "recommendation"
]]

final_output

    candidate_id                                        resume_text                                   skills_extracted  experience_extracted     education_extracted  certifications_extracted  keyword_match_count  keyword_score  similarity_score  experience_score  education_score  certification_score  final_score recommendation
0              1  Aarav has skills in Python, SQL, Excel, and Ma...           Python, SQL, Excel, and Machine Learning                     3  B.Tech. Certifications                         2                    3          0.375          0.432462          0.500000              NaN                 0.50          NaN        Low Fit
1              2  Diya has skills in Recruitment, Onboarding, Co...  Recruitment, Onboarding, Communication, and Excel                     4  MBA HR. Certifications                         1                    2          0.250          0.232806          0.666667              NaN                 0.25          NaN        Low Fit
2              3  Kabir has skills in Python, SQL, Tableau, Data...    Python, SQL, Tableau, Data Analysis, and Pandas                     2    B.Sc. Certifications                         3                    2          0.250          0.107773          0.333333              NaN                 0.75          NaN        Low Fit
3              4  Ishita has skills in Java, SQL, Spring, Teamwo...     Java, SQL, Spring, Teamwork, and Communication                     5  B.Tech. Certifications                         2                    2          0.250          0.122363          0.833333              NaN                 0.50          NaN        Low Fit
4              5  Vivaan has skills in Python, SQL, Deep Learnin...          Python, SQL, Deep Learning, NLP, and BERT                     6  M.Tech. Certifications                         4                    3          0.375          0.354681          1.000000              NaN                 1.00          NaN        Low Fit
5              6  Anaya has skills in Recruitment, Sourcing, Int...  Recruitment, Sourcing, Interview Screening, an...                     3  MBA HR. Certifications                         2                    2          0.250          0.179471          0.500000              NaN                 0.50          NaN        Low Fit
6              7  Reyansh has skills in Python, SQL, Power BI, E...       Python, SQL, Power BI, Excel, and Statistics                     4  B.Tech. Certifications                         2                    3          0.375          0.442718          0.666667              NaN                 0.50          NaN        Low Fit
7              8  Myra has skills in Machine Learning, Python, T...  Machine Learning, Python, Tableau, and Data Vi...                     2    M.Sc. Certifications                         3                    2          0.250          0.261416          0.333333              NaN                 0.75          NaN        Low Fit
8              9  Arjun has skills in Manual Testing, Selenium, ...  Manual Testing, Selenium, Jira, and Communication                     5     BCA. Certifications                         1                    1          0.125          0.059033          0.833333              NaN                 0.25          NaN        Low Fit
9             10  Siya has skills in Python, SQL, NLP, ML, Commu...  Python, SQL, NLP, ML, Communication, and Teamwork                     3     MCA. Certifications                         3                    4          0.500          0.331545          0.500000              NaN                 0.75          NaN        Low Fit
10            11  Krish has skills in Excel, SQL, Dashboarding, ...  Excel, SQL, Dashboarding, Reporting, and Power BI                     2   B.Com. Certifications                         2                    2          0.250          0.321523          0.333333              NaN                 0.50          NaN        Low Fit
11            12  Aadhya has skills in Python, R, Statistics, an...        Python, R, Statistics, and Machine Learning                     4  M.Stat. Certifications                         3                    2          0.250          0.358262          0.666667              NaN                 0.75          NaN        Low Fit
12            13  Advik has skills in Project Management, Agile,...  Project Management, Agile, Scrum, and Communic...                     6     MBA. Certifications                         2                    1          0.125          0.059033          1.000000              NaN                 0.50          NaN        Low Fit
13            14  Kiara has skills in Python, SQL, Data Analysis...  Python, SQL, Data Analysis, Recruitment, and H...                     5  MBA HR. Certifications                         4                    4          0.500          0.386489          0.833333              NaN                 1.00          NaN        Low Fit
14            15  Atharv has skills in C++, Algorithms, Data Str...  C++, Algorithms, Data Structures, and Problem ...                     0  B.Tech. Certifications                         1                    0          0.000          0.000000          0.000000              NaN                 0.25          NaN        Low Fit
15            16  Navya has skills in Python, SQL, Tableau, Powe...  Python, SQL, Tableau, Power BI, and Communication                     3     BBA. Certifications                         2                    4          0.500          0.540387          0.500000              NaN                 0.50          NaN        Low Fit
16            17  Rudra has skills in NLP, BERT, Transformers, P...  NLP, BERT, Transformers, Python, and Machine L...                     5  M.Tech. Certifications                         4                    3          0.375          0.397459          0.833333              NaN                 1.00          NaN        Low Fit
17            18  Sara has skills in Recruitment Analytics, Exce...  Recruitment Analytics, Excel, Communication, a...                     4  MBA HR. Certifications                         2                    3          0.375          0.346614          0.666667              NaN                 0.50          NaN        Low Fit
18            19  Vihaan has skills in Python, SQL, Statistics, ...  Python, SQL, Statistics, Data Cleaning, and Pa...                     2    B.Sc. Certifications                         2                    2          0.250          0.104096          0.333333              NaN                 0.50          NaN        Low Fit
19            20  Meera has skills in Python, Machine Learning, ...  Python, Machine Learning, SQL, Communication, ...                     4     MCA. Certifications                         3                    4          0.500          0.435013          0.666667              NaN                 0.75          NaN        Low Fit

In [22]:
final_output.to_csv("resume_parsing_screening_output.csv", index=False)
print("File saved successfully.")

File saved successfully.

In [23]:
from google.colab import files

files.download("resume_parsing_screening_output.csv")